# Generated by Django 4.1.5 on 2023-01-22 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlmodel',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 22, 2, 11, 48, 264906)),
        ),
    ]
