# Generated by Django 4.1.5 on 2023-01-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_xmlmodel_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlmodel',
            name='image_xml',
            field=models.ImageField(default='app/static/img/image_xml.webp', upload_to=''),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 2, 20, 53, 844046)),
        ),
    ]
