# Generated by Django 4.1.5 on 2023-01-22 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_xmlmodel_image_xml_alter_xmlmodel_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 2, 56, 0, 141758)),
        ),
    ]
