# Generated by Django 4.1.5 on 2023-01-22 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_xmlmodel_fecha_alter_xmlmodel_image_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 6, 6, 48, 936107, tzinfo=datetime.timezone.utc)),
        ),
    ]
